<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4N9JI20" failures="1" tests="7" name="Default test" time="0.114" errors="0" timestamp="2021-02-26T22:36:15 IST">
  <testcase classname="ad.testCalculator" name="emptyStringAnswerNull" time="0.017"/>
  <testcase classname="ad.testCalculator" name="multivalueCommaDelimiterAnswer" time="0.008"/>
  <testcase classname="ad.testCalculator" name="singleValuedAnswer" time="0.002"/>
  <testcase classname="ad.testCalculator" name="supportDifferentDelimeter" time="0.002"/>
  <testcase classname="ad.testCalculator" name="throwsOnNegativeNumber" time="0.002">
    <failure type="org.testng.TestException" message="
Method testCalculator.throwsOnNegativeNumber()[pri:0, instance:ad.testCalculator@7d3a22a9] should have thrown an exception of type class java.lang.IllegalArgumentException">
      <![CDATA[org.testng.TestException: 
Method testCalculator.throwsOnNegativeNumber()[pri:0, instance:ad.testCalculator@7d3a22a9] should have thrown an exception of type class java.lang.IllegalArgumentException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:747)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:635)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- throwsOnNegativeNumber -->
  <testcase classname="ad.testCalculator" name="twoValueCommaDelimiterAnswer" time="0.002"/>
  <testcase classname="ad.testCalculator" name="twoValueNewLineDelimiterAnswer" time="0.002"/>
</testsuite> <!-- Default test -->
